### ISSUE TITLE
持续处于getting translation状态

### ISSUE THREAD

**Issue by dooozo** [douo/raycast-openai-translator#1]
<img width="1440" alt="截屏2023-03-14 00 35 53" src="https://user-images.githubusercontent.com/76516545/224766927-14dce05e-cdcb-4458-9c3d-54d3f9e06c94.png">
作者您好，请问这个bug有修复方法吗，试过换API之类的方式并不能解决。谢谢作者。

**Comment by douo** [comment]
终端试试看你的 api entrypoint 能成功响应吗？`curl -X GET https://api.openai.com/v1/chat/completions  --verbose` 
看起来像是被墙了，需要后面加上 Proxy 支持。

**Comment by douo** [comment]
你可以测试一下这个 entrypoint:  https://chatgpt-api.shn.hk/v1 
注意需要先更新到最新版本，参考一下这个 [tweet](https://twitter.com/dourok/status/1635542213831831552)，不然 API key 可能有泄漏风险。

**Comment by will-zhang** [comment]
> 终端试试看你的 api entrypoint 能成功响应吗？`curl -X GET https://api.openai.com/v1/chat/completions --verbose` 看起来像是被墙了，需要后面加上 Proxy 支持。

我测试了这个是能访问的，但是还是持续处于getting translation状态

**Comment by onezero-10** [comment]
看来我也遇到了同样的问题，一直处于getting you translation...

**Comment by Chunwei-Wu** [comment]
作者您好，我发现我可以使用openai-translator正常翻译，但是使用raycast-openai-translator会一直getting you translation，请问这是因为缺乏Proxy 支持吗？
此外，我参考了上面tweet的方法，报以下错误：
<img width="374" alt="image" src="https://user-images.githubusercontent.com/28524375/228920494-1bae3503-df95-4bcc-8944-dac6d9eaac91.png">
这是由于未更新到最新版本的原因吗？

谢谢作者，祝好

**Comment by douo** [comment]
@Chunwei-Wu 这个 API 已经失效了
> 2023-03-26: It is with a heavy heart that I announce the archiving of the ChatGPTAPIFree repository. Our endeavour to provide a free API for all has reached an unsustainable financial crossroad, prompting a temporary halt in our pursuit of equal access to AI technology. Despite this setback, our commitment remains unwavering. We will continue to explore alternative methods and advocate for OpenAI to lower their API pricing and remove regional restrictions. While our progress may have slowed, our resolve to create a world where the power of AI is accessible to all is stronger than ever.
https://github.com/ayaka14732/ChatGPTAPIFree

接下来我加个 socks5 代理吧或者看看 openai-translator 有没有加了什么 fancy work. 合理这块应用层能做的不多。

**Comment by Chunwei-Wu** [comment]
感谢作者的回复，期待新版本～

**Comment by douo** [comment]
已经上线支持 SOCKS5 代理和 15s CONNECTION_TIMEOUT 的版本
